/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author marielamejiagtz
 */
public class InterfazCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCalculadora
     */
    

    public InterfazCalculadora() {
        initComponents();
        pantallaTxt.setEnabled(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaTxt = new javax.swing.JTextField();
        unoBt1 = new javax.swing.JButton();
        dosBt = new javax.swing.JButton();
        tresBt = new javax.swing.JButton();
        cuatroBt = new javax.swing.JButton();
        seisBt = new javax.swing.JButton();
        cincoBt = new javax.swing.JButton();
        ochoBt = new javax.swing.JButton();
        nueveBt = new javax.swing.JButton();
        sieteBt = new javax.swing.JButton();
        ceroBt = new javax.swing.JButton();
        menosBt = new javax.swing.JButton();
        sumaBt = new javax.swing.JButton();
        multiplicacionBt = new javax.swing.JButton();
        enterBt = new javax.swing.JButton();
        divisionBt1 = new javax.swing.JButton();
        puntoBt = new javax.swing.JButton();
        parentesisCerradoBt = new javax.swing.JButton();
        parentesisAbiertoBt1 = new javax.swing.JButton();
        delBt = new javax.swing.JButton();
        borrarACBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        pantallaTxt.setBackground(new java.awt.Color(204, 204, 204));
        pantallaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaTxtActionPerformed(evt);
            }
        });

        unoBt1.setBackground(new java.awt.Color(0, 204, 153));
        unoBt1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        unoBt1.setText("1");
        unoBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBt1ActionPerformed(evt);
            }
        });

        dosBt.setBackground(new java.awt.Color(0, 204, 153));
        dosBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        dosBt.setText("2");
        dosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBtActionPerformed(evt);
            }
        });

        tresBt.setBackground(new java.awt.Color(0, 204, 153));
        tresBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        tresBt.setText("3");
        tresBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBtActionPerformed(evt);
            }
        });

        cuatroBt.setBackground(new java.awt.Color(0, 204, 153));
        cuatroBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cuatroBt.setText("4");
        cuatroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBtActionPerformed(evt);
            }
        });

        seisBt.setBackground(new java.awt.Color(0, 204, 153));
        seisBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        seisBt.setText("6");
        seisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtActionPerformed(evt);
            }
        });

        cincoBt.setBackground(new java.awt.Color(0, 204, 153));
        cincoBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cincoBt.setText("5");
        cincoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBtActionPerformed(evt);
            }
        });

        ochoBt.setBackground(new java.awt.Color(0, 204, 153));
        ochoBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ochoBt.setText("8");
        ochoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBtActionPerformed(evt);
            }
        });

        nueveBt.setBackground(new java.awt.Color(0, 204, 153));
        nueveBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        nueveBt.setText("9");
        nueveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBtActionPerformed(evt);
            }
        });

        sieteBt.setBackground(new java.awt.Color(0, 204, 153));
        sieteBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        sieteBt.setText("7");
        sieteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBtActionPerformed(evt);
            }
        });

        ceroBt.setBackground(new java.awt.Color(0, 204, 153));
        ceroBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ceroBt.setText("0");
        ceroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBtActionPerformed(evt);
            }
        });

        menosBt.setBackground(new java.awt.Color(0, 204, 153));
        menosBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        menosBt.setText("-");
        menosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosBtActionPerformed(evt);
            }
        });

        sumaBt.setBackground(new java.awt.Color(0, 204, 153));
        sumaBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        sumaBt.setText("+");
        sumaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBtActionPerformed(evt);
            }
        });

        multiplicacionBt.setBackground(new java.awt.Color(0, 204, 153));
        multiplicacionBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        multiplicacionBt.setText("*");
        multiplicacionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionBtActionPerformed(evt);
            }
        });

        enterBt.setBackground(new java.awt.Color(0, 204, 153));
        enterBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        enterBt.setText("=");
        enterBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtActionPerformed(evt);
            }
        });

        divisionBt1.setBackground(new java.awt.Color(0, 204, 153));
        divisionBt1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        divisionBt1.setText("/");
        divisionBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionBt1ActionPerformed(evt);
            }
        });

        puntoBt.setBackground(new java.awt.Color(0, 204, 153));
        puntoBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        puntoBt.setText(".");
        puntoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBtActionPerformed(evt);
            }
        });

        parentesisCerradoBt.setBackground(new java.awt.Color(0, 204, 153));
        parentesisCerradoBt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        parentesisCerradoBt.setText(")");
        parentesisCerradoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisCerradoBtActionPerformed(evt);
            }
        });

        parentesisAbiertoBt1.setBackground(new java.awt.Color(0, 204, 153));
        parentesisAbiertoBt1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        parentesisAbiertoBt1.setText("(");
        parentesisAbiertoBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisAbiertoBt1ActionPerformed(evt);
            }
        });

        delBt.setBackground(new java.awt.Color(0, 204, 153));
        delBt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        delBt.setText("DEL");
        delBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtActionPerformed(evt);
            }
        });

        borrarACBt.setBackground(new java.awt.Color(0, 204, 153));
        borrarACBt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        borrarACBt.setText("AC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(pantallaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cuatroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cincoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unoBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(dosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sieteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ochoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ceroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sumaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parentesisAbiertoBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divisionBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(delBt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarACBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesisCerradoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacionBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pantallaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarACBt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cincoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuatroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesisAbiertoBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesisCerradoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ceroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puntoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(divisionBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplicacionBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(enterBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaTxtActionPerformed
    /**/
    private void unoBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unoBt1ActionPerformed

    private void dosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosBtActionPerformed

    private void tresBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresBtActionPerformed

    private void cuatroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuatroBtActionPerformed

    private void seisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisBtActionPerformed

    private void cincoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoBtActionPerformed

    private void ochoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ochoBtActionPerformed

    private void nueveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueveBtActionPerformed

    private void sieteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sieteBtActionPerformed

    private void ceroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceroBtActionPerformed

    private void menosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosBtActionPerformed

    private void sumaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaBtActionPerformed

    private void multiplicacionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiplicacionBtActionPerformed

    private void enterBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterBtActionPerformed

    private void divisionBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divisionBt1ActionPerformed

    private void puntoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntoBtActionPerformed

    private void parentesisCerradoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisCerradoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentesisCerradoBtActionPerformed

    private void parentesisAbiertoBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisAbiertoBt1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_parentesisAbiertoBt1ActionPerformed

    private void delBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_delBtActionPerformed
    private void borrarACBtPerformed(java.awt.event.ActionEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton borrarACBt;
    protected javax.swing.JButton ceroBt;
    protected javax.swing.JButton cincoBt;
    protected javax.swing.JButton cuatroBt;
    protected javax.swing.JButton delBt;
    protected javax.swing.JButton divisionBt1;
    protected javax.swing.JButton dosBt;
    protected javax.swing.JButton enterBt;
    protected javax.swing.JButton menosBt;
    protected javax.swing.JButton multiplicacionBt;
    protected javax.swing.JButton nueveBt;
    protected javax.swing.JButton ochoBt;
    public javax.swing.JTextField pantallaTxt;
    protected javax.swing.JButton parentesisAbiertoBt1;
    protected javax.swing.JButton parentesisCerradoBt;
    protected javax.swing.JButton puntoBt;
    protected javax.swing.JButton seisBt;
    protected javax.swing.JButton sieteBt;
    protected javax.swing.JButton sumaBt;
    protected javax.swing.JButton tresBt;
    protected javax.swing.JButton unoBt1;
    // End of variables declaration//GEN-END:variables
}
